### ISSUE TITLE
Can this be updated for PHP 7.1/7.2?

### ISSUE THREAD

**Issue by skyzyx** [rskuipers/php-assumptions#21]
It's currently using an older version of php-parser which doesn't support modern PHP.

**Comment by rskuipers** [comment]
@skyzyx That's not really true, it supports PHP 7.1 as it is now.
I did add PHP 7.1 to the Travis version matrix to proof this: https://travis-ci.org/rskuipers/php-assumptions/builds/270842424

**Comment by RusAlex** [comment]
Will not open new issue. But 0.5.0 do not support destructuring assignment in the way: 

``` 
// [] style
["id" => $id1, "name" => $name1] = $data[0];
```

This seems like php-parser problem.

http://php.net/manual/en/migration71.new-features.php#migration71.new-features.support-for-keys-in-list

**Comment by EvgenyOrekhov** [comment]
rskuipers/php-assumptions:dev-master works fine with php-parser 3.1.4 and PHP 7.2. Though we don't use destructuring assignments in our project.

**Comment by rskuipers** [comment]
I just released 0.6.0 which should support PHP 7.1.
