### ISSUE TITLE
Use non-zero exit code when assumptions are found

### ISSUE THREAD

**Issue by EvgenyOrekhov** [rskuipers/php-assumptions#24]
I want PHP Assumptions to break my CI build when assumptions are found.

**Comment by rskuipers** [comment]
@EvgenyOrekhov Unfortunately php-assumptions reports false-positives in its current state, so I wouldn't recommend having it break your build. But perhaps a flag to make this optional would work.

**Comment by EvgenyOrekhov** [comment]
@rskuipers Are you planning to make php-assumptions not report false-positives? Is it even feasible?

**Comment by rskuipers** [comment]
@EvgenyOrekhov I don't think it's feasible. To be fair, I think with PHP 7 it makes a lot more sense to assert you are using type-hints properly to prevent making assumptions in your code.

So any tool that can enforce that probably performs better than the analysis `php-assumptions` currently makes.

**Comment by EvgenyOrekhov** [comment]
@rskuipers There are a lot of frameworks and libraries that have methods that return something like `null|bool|SomeClass`, and there is no any other tool that I know of that catches the `!== null` assumptions.

**Comment by rskuipers** [comment]
@EvgenyOrekhov Now available in version 0.7.1
