### ISSUE TITLE
Unable to install stable version due to nikic/php-parser 2.0

### ISSUE THREAD

**Issue by EvgenyOrekhov** [rskuipers/php-assumptions#25]
Composer refuses to install stable version of PHP Assumptions because my project requires nikic/php-parser ^3.0.

I can see that it is fixed in a9ca134e598d9e361c713332e1aa62400fdadf97, and I was able to install rskuipers/php-assumptions:dev-master, but I would prefer to use a stable version.

Could you please release a new stable version?

**Comment by rskuipers** [comment]
@EvgenyOrekhov I just released 0.6.0, you should be able to pull that in through composer now.

https://packagist.org/packages/rskuipers/php-assumptions
