### ISSUE TITLE
Feature request: could you add a --version flag

### ISSUE THREAD

**Issue by MetalArend** [rskuipers/php-assumptions#28]
Would it be possible to add a --version flag to this library, to quickly check which version one is running?

**Comment by rskuipers** [comment]
@MetalArend Sounds good to me! Will see if I have some spare time this weekend. Of course you're also free to contribute it.

**Comment by MetalArend** [comment]
Would love to :D Alas I'm currently spending my spare time on getting all the phpqa.io images up-to-date for the moment, and making sure they stay up-to-date in the future. Thanks for looking into it, it helps a lot: https://github.com/phpqa/phpa/blob/master/Makefile#L15
