### ISSUE TITLE
Add support for nikic/php-parser 4.0.0

### ISSUE THREAD

**Issue by EvgenyOrekhov** [rskuipers/php-assumptions#30]
Composer refuses to install PHP Assumptions because it requires nikic/php-parser ^2.0|^3.0, but my project requires nikic/php-parser ^4.0.

**Comment by fisharebest** [comment]
Useful documentation here: https://github.com/nikic/PHP-Parser/blob/master/UPGRADE-4.0.md

**Comment by ruimelodev** [comment]
I'm facing the same problem.
@rskuipers can you make a release update for `nikic/php-parser ^4.0.`?
Thank you!

**Comment by rskuipers** [comment]
@ruimelodev That's unfortunate. I'm currently not actively using this project and don't have the time to do this upgrade. If you have the time to upgrade it then I'd be happy to review your PR and do a new release.

**Comment by segrax** [comment]
Have created PR #34 which adds support for php-parser 4

**Comment by rskuipers** [comment]
Resolved in 0.8.0 thanks to @segrax 

https://packagist.org/packages/rskuipers/php-assumptions#0.8.0
