### ISSUE TITLE
Deprecated error: passing `null` to `strlen`

### ISSUE THREAD

**Issue by niconoe-** [rskuipers/php-assumptions#37]
I tried the v0.8.0 on one of my project and I got the following error

```
Deprecated: strlen(): Passing null to parameter #1 ($string) of type string is deprecated in /var/www/www/vendor/rskuipers/php-assumptions/src/PhpAssumptions/Cli.php on line 138
```

I ran the project in a docker container that own a PHP 8.1 version.

To fix it, the following line : 
https://github.com/rskuipers/php-assumptions/blob/master/src/PhpAssumptions/Cli.php#L138

 could definitly be replaced by

```php
if ($list !== '') {
```

as the only purpose of the usage of `strlen` here is to check if the string is not empty.

EDIT: the only usage I found is actually here:
https://github.com/rskuipers/php-assumptions/blob/10f82ca2a268d6624553d2de4659ed6451d9ac60/src/PhpAssumptions/Cli.php#L105

After a quick look at `\League\CLImate\Argument\Manager::get` method, I found out it can return `null`. As the argument of `getPathsFromList` is supposed to be a `string` (read from PHPDoc + inferred from usage in the method), I think a cast should be executed while passing the argument:
```php
$excludes = $this->getPathsFromList((string)$this->cli->arguments->get('exclude'));
```

Indeed, the return type of `\League\CLImate\Argument\Manager::get` is `string|int|float|bool|null`, all of them castable to string.

**Comment by rskuipers** [comment]
Thank you for your contribution and the detailed explanation!

I merged it and I've created a new tag you can now use: https://github.com/rskuipers/php-assumptions/releases/tag/0.8.1

**Comment by niconoe-** [comment]
You're welcome! I liked to contribute :+1:
